HPCloud-PHP: Flavor Class Reference
Flavor Class Reference
Class for working with Database Flavors.
Public Member Functions
__construct ($token, $projectId, $endpoint)
listFlavors ()
Retrieve a list of available instance flavors.
getFlavorByName ($name)
Get a FlavorDetails object by its name.
Protected Attributes
$token
$projectId
$url
$client
Protected Attributes inherited from Operations
$token
$projectId
Additional Inherited Members
Protected Member Functions inherited from Operations
headers ($merge=array())
Generate the base headers needed by DBaaS requests.
Detailed Description
Class for working with Database Flavors.
Definition at line 35 of file Flavor.php.
Constructor & Destructor Documentation
__construct ($token, $projectId, $endpoint)
Definition at line 42 of file Flavor.php.
References $endpoint, DBaaS\$projectId, DBaaS\$token, DBaaS\instance(), DBaaS\projectId(), and DBaaS\url().
Member Function Documentation
getFlavorByName ($name)
Get a FlavorDetails object by its name.
Parameters
string $name The name of the flavor.
Return values
HPCloud::Services::DBaaS::FlavorDetails
Returns
A flavor details object for the flavor.
Definition at line 80 of file Flavor.php.
References $name, and Flavor\listFlavors().
listFlavors ()
Retrieve a list of available instance flavors.
Return values
array
Returns
array An array of objects listing the available flavors.
Definition at line 57 of file Flavor.php.
References DBaaS\$url, Operations\headers(), and DBaaS\url().
Referenced by Flavor\getFlavorByName().
Member Data Documentation
$client protected
Definition at line 40 of file Flavor.php.
$projectId protected
Definition at line 38 of file Flavor.php.
$token protected
Definition at line 37 of file Flavor.php.
$url protected
Definition at line 39 of file Flavor.php.
The documentation for this class was generated from the following file:
src/HPCloud/Services/DBaaS/Flavor.php