HPCloud-PHP: Operations Class Reference
Operations Class Reference
Abstract class for DBaaS Operations groups.
Protected Member Functions
headers ($merge=array())
Generate the base headers needed by DBaaS requests.
Protected Attributes
$token
$projectId
Detailed Description
Abstract class for DBaaS Operations groups.
DBaaS operations have some structural similarities that can be shared between instance and snapshot operation groups. These are encapsulated here.
Definition at line 16 of file Operations.php.
Member Function Documentation
headers ($merge = array()) protected
Generate the base headers needed by DBaaS requests.
Definition at line 23 of file Operations.php.
References DBaaS\projectId().
Referenced by Instance\create(), Snapshot\create(), Instance\delete(), Snapshot\delete(), Instance\describe(), Snapshot\describe(), Flavor\listFlavors(), Instance\listInstances(), Snapshot\listSnapshots(), Instance\resetPassword(), and Instance\restart().
Member Data Documentation
$projectId protected
Definition at line 18 of file Operations.php.
$token protected
Definition at line 17 of file Operations.php.
The documentation for this class was generated from the following file:
src/HPCloud/Services/DBaaS/Operations.php