HPCloud-PHP: Subdir Class Reference
Subdir Class Reference
Represent a subdirectory (subdir) entry.
Public Member Functions
__construct ($path, $delimiter= '/')
Create a new subdirectory.
path ()
Get the path.
delimiter ()
Get the delimiter used by the server.
Protected Attributes
$path
$delimiter
Detailed Description
Represent a subdirectory (subdir) entry.
Depending on the method with which Swift container requests are executed, Swift may return subdir entries instead of Objects.
Subdirs are used for things that are directory-like.
Definition at line 37 of file Subdir.php.
Constructor & Destructor Documentation
__construct ($path, $delimiter = '/')
Create a new subdirectory.
This represents a remote response's tag for a subdirectory.
Parameters
string $path The path string that this subdir describes.
string $delimiter The delimiter used in this path.
Definition at line 53 of file Subdir.php.
References Subdir\$delimiter, Subdir\$path, Subdir\delimiter(), and Subdir\path().
Member Function Documentation
delimiter ()
Get the delimiter used by the server.
Return values
string
Returns
string The value used as a delimiter.
Definition at line 77 of file Subdir.php.
Referenced by Subdir\__construct().
path ()
Get the path.
The path is delimited using the string returned by delimiter().
Return values
string
Returns
string The path.
Definition at line 67 of file Subdir.php.
Referenced by Subdir\__construct().
Member Data Documentation
$delimiter protected
Definition at line 40 of file Subdir.php.
Referenced by Subdir\__construct().
$path protected
Definition at line 39 of file Subdir.php.
Referenced by Subdir\__construct().
The documentation for this class was generated from the following file:
src/HPCloud/Storage/ObjectStorage/Subdir.php